// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	CreateApplicationAssessment(ctx context.Context, arg CreateApplicationAssessmentParams) error
	CreateApplicationDocument(ctx context.Context, arg CreateApplicationDocumentParams) error
	CreateBuildingApproval(ctx context.Context, arg CreateBuildingApprovalParams) error
	CreateHealthCertificate(ctx context.Context, arg CreateHealthCertificateParams) error
	CreateSeasonalParkingTicket(ctx context.Context, arg CreateSeasonalParkingTicketParams) error
	CreateSingleBusinessPermit(ctx context.Context, arg CreateSingleBusinessPermitParams) error
	GetApplicationByID(ctx context.Context, id uuid.UUID) (GetApplicationByIDRow, error)
	ListApplicationsByTaxpayer(ctx context.Context, taxpayerID uuid.UUID) ([]ListApplicationsByTaxpayerRow, error)
	UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) error
}

var _ Querier = (*Queries)(nil)
