// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteTaxpayer(ctx context.Context, id uuid.UUID) error
	GetTaxpayerByID(ctx context.Context, id uuid.UUID) (Taxpayer, error)
	GetTaxpayerByNationalID(ctx context.Context, nationalID string) (Taxpayer, error)
	InsertTaxpayer(ctx context.Context, arg InsertTaxpayerParams) (Taxpayer, error)
	ListTaxpayers(ctx context.Context, arg ListTaxpayersParams) ([]Taxpayer, error)
	UpdateTaxpayer(ctx context.Context, arg UpdateTaxpayerParams) (Taxpayer, error)
}

var _ Querier = (*Queries)(nil)
