// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: taxpayer.sql

package models

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteTaxpayer = `-- name: DeleteTaxpayer :exec
DELETE FROM taxpayers WHERE id = $1
`

func (q *Queries) DeleteTaxpayer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTaxpayer, id)
	return err
}

const getFullProfileByUserID = `-- name: GetFullProfileByUserID :one
SELECT u.id, u.email as u_email, u.first_name as u_first_name, u.last_name as u_last_name, u.phone_number as u_phone,
       u.role, u.created_at as u_created_at,
       t.county_id, t.taxpayer_type, t.national_id, t.email as t_email, t.phone_number as t_phone,
       t.first_name, t.last_name, t.business_name, t.created_at as t_created_at, t.updated_at
FROM users u
JOIN taxpayers t ON u.id = t.user_id
WHERE u.id = $1 AND u.is_active = true
`

type GetFullProfileByUserIDRow struct {
	ID           uuid.UUID      `json:"id"`
	UEmail       string         `json:"u_email"`
	UFirstName   string         `json:"u_first_name"`
	ULastName    string         `json:"u_last_name"`
	UPhone       sql.NullString `json:"u_phone"`
	Role         string         `json:"role"`
	UCreatedAt   sql.NullTime   `json:"u_created_at"`
	CountyID     int32          `json:"county_id"`
	TaxpayerType string         `json:"taxpayer_type"`
	NationalID   string         `json:"national_id"`
	TEmail       string         `json:"t_email"`
	TPhone       sql.NullString `json:"t_phone"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	BusinessName sql.NullString `json:"business_name"`
	TCreatedAt   sql.NullTime   `json:"t_created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetFullProfileByUserID(ctx context.Context, userID uuid.UUID) (GetFullProfileByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFullProfileByUserID, userID)
	var i GetFullProfileByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UEmail,
		&i.UFirstName,
		&i.ULastName,
		&i.UPhone,
		&i.Role,
		&i.UCreatedAt,
		&i.CountyID,
		&i.TaxpayerType,
		&i.NationalID,
		&i.TEmail,
		&i.TPhone,
		&i.FirstName,
		&i.LastName,
		&i.BusinessName,
		&i.TCreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaxpayerByID = `-- name: GetTaxpayerByID :one
SELECT id, county_id, user_id, taxpayer_type, national_id, email, phone_number,
       first_name, last_name, business_name, created_at, updated_at
FROM taxpayers
WHERE id = $1
`

type GetTaxpayerByIDRow struct {
	ID           uuid.UUID      `json:"id"`
	CountyID     int32          `json:"county_id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	TaxpayerType string         `json:"taxpayer_type"`
	NationalID   string         `json:"national_id"`
	Email        string         `json:"email"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	BusinessName sql.NullString `json:"business_name"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetTaxpayerByID(ctx context.Context, id uuid.UUID) (GetTaxpayerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTaxpayerByID, id)
	var i GetTaxpayerByIDRow
	err := row.Scan(
		&i.ID,
		&i.CountyID,
		&i.UserID,
		&i.TaxpayerType,
		&i.NationalID,
		&i.Email,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.BusinessName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaxpayerByNationalID = `-- name: GetTaxpayerByNationalID :one
SELECT id, county_id, user_id, taxpayer_type, national_id, email, phone_number,
       first_name, last_name, business_name, created_at, updated_at
FROM taxpayers
WHERE national_id = $1
`

type GetTaxpayerByNationalIDRow struct {
	ID           uuid.UUID      `json:"id"`
	CountyID     int32          `json:"county_id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	TaxpayerType string         `json:"taxpayer_type"`
	NationalID   string         `json:"national_id"`
	Email        string         `json:"email"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	BusinessName sql.NullString `json:"business_name"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetTaxpayerByNationalID(ctx context.Context, nationalID string) (GetTaxpayerByNationalIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTaxpayerByNationalID, nationalID)
	var i GetTaxpayerByNationalIDRow
	err := row.Scan(
		&i.ID,
		&i.CountyID,
		&i.UserID,
		&i.TaxpayerType,
		&i.NationalID,
		&i.Email,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.BusinessName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaxpayerByUserID = `-- name: GetTaxpayerByUserID :one
SELECT id, county_id, user_id, taxpayer_type, national_id, email, phone_number,
       first_name, last_name, business_name, created_at, updated_at
FROM taxpayers
WHERE user_id = $1
`

type GetTaxpayerByUserIDRow struct {
	ID           uuid.UUID      `json:"id"`
	CountyID     int32          `json:"county_id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	TaxpayerType string         `json:"taxpayer_type"`
	NationalID   string         `json:"national_id"`
	Email        string         `json:"email"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	BusinessName sql.NullString `json:"business_name"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetTaxpayerByUserID(ctx context.Context, userID uuid.NullUUID) (GetTaxpayerByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTaxpayerByUserID, userID)
	var i GetTaxpayerByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.CountyID,
		&i.UserID,
		&i.TaxpayerType,
		&i.NationalID,
		&i.Email,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.BusinessName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTaxpayer = `-- name: InsertTaxpayer :one
INSERT INTO taxpayers (
    county_id, user_id, taxpayer_type, national_id, email, phone_number, 
    first_name, last_name, business_name
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9
)
RETURNING id, user_id, county_id, taxpayer_type, national_id, email, phone_number, first_name, last_name, business_name, created_at, updated_at
`

type InsertTaxpayerParams struct {
	CountyID     int32          `json:"county_id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	TaxpayerType string         `json:"taxpayer_type"`
	NationalID   string         `json:"national_id"`
	Email        string         `json:"email"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	BusinessName sql.NullString `json:"business_name"`
}

type InsertTaxpayerRow struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	CountyID     int32          `json:"county_id"`
	TaxpayerType string         `json:"taxpayer_type"`
	NationalID   string         `json:"national_id"`
	Email        string         `json:"email"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	BusinessName sql.NullString `json:"business_name"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

func (q *Queries) InsertTaxpayer(ctx context.Context, arg InsertTaxpayerParams) (InsertTaxpayerRow, error) {
	row := q.db.QueryRowContext(ctx, insertTaxpayer,
		arg.CountyID,
		arg.UserID,
		arg.TaxpayerType,
		arg.NationalID,
		arg.Email,
		arg.PhoneNumber,
		arg.FirstName,
		arg.LastName,
		arg.BusinessName,
	)
	var i InsertTaxpayerRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CountyID,
		&i.TaxpayerType,
		&i.NationalID,
		&i.Email,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.BusinessName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaxpayers = `-- name: ListTaxpayers :many
SELECT id, county_id, user_id, taxpayer_type, national_id, email, phone_number,
       first_name, last_name, business_name, created_at, updated_at
FROM taxpayers
WHERE county_id = $3
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListTaxpayersParams struct {
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
	CountyID int32 `json:"county_id"`
}

type ListTaxpayersRow struct {
	ID           uuid.UUID      `json:"id"`
	CountyID     int32          `json:"county_id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	TaxpayerType string         `json:"taxpayer_type"`
	NationalID   string         `json:"national_id"`
	Email        string         `json:"email"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	BusinessName sql.NullString `json:"business_name"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

func (q *Queries) ListTaxpayers(ctx context.Context, arg ListTaxpayersParams) ([]ListTaxpayersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaxpayers, arg.Limit, arg.Offset, arg.CountyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaxpayersRow
	for rows.Next() {
		var i ListTaxpayersRow
		if err := rows.Scan(
			&i.ID,
			&i.CountyID,
			&i.UserID,
			&i.TaxpayerType,
			&i.NationalID,
			&i.Email,
			&i.PhoneNumber,
			&i.FirstName,
			&i.LastName,
			&i.BusinessName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaxpayer = `-- name: UpdateTaxpayer :one
UPDATE taxpayers
SET
    email = $1,
    phone_number = $2,
    first_name = $3,
    last_name = $4,
    business_name = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $6
RETURNING id, county_id, taxpayer_type, national_id, email, phone_number, first_name, last_name, business_name, created_at, updated_at
`

type UpdateTaxpayerParams struct {
	Email        string         `json:"email"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	BusinessName sql.NullString `json:"business_name"`
	ID           uuid.UUID      `json:"id"`
}

type UpdateTaxpayerRow struct {
	ID           uuid.UUID      `json:"id"`
	CountyID     int32          `json:"county_id"`
	TaxpayerType string         `json:"taxpayer_type"`
	NationalID   string         `json:"national_id"`
	Email        string         `json:"email"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	BusinessName sql.NullString `json:"business_name"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpdateTaxpayer(ctx context.Context, arg UpdateTaxpayerParams) (UpdateTaxpayerRow, error) {
	row := q.db.QueryRowContext(ctx, updateTaxpayer,
		arg.Email,
		arg.PhoneNumber,
		arg.FirstName,
		arg.LastName,
		arg.BusinessName,
		arg.ID,
	)
	var i UpdateTaxpayerRow
	err := row.Scan(
		&i.ID,
		&i.CountyID,
		&i.TaxpayerType,
		&i.NationalID,
		&i.Email,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.BusinessName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
