// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Assessment struct {
	ID               uuid.UUID     `json:"id"`
	CountyID         int32         `json:"county_id"`
	TaxpayerID       uuid.UUID     `json:"taxpayer_id"`
	RevenueID        uuid.NullUUID `json:"revenue_id"`
	AssessmentNumber string        `json:"assessment_number"`
	AssessmentType   string        `json:"assessment_type"`
	FinancialYear    string        `json:"financial_year"`
	BaseAmount       string        `json:"base_amount"`
	CalculatedAmount string        `json:"calculated_amount"`
	TotalAmount      string        `json:"total_amount"`
	Status           string        `json:"status"`
	DueDate          time.Time     `json:"due_date"`
	AssessedBy       uuid.NullUUID `json:"assessed_by"`
	AssessedDate     time.Time     `json:"assessed_date"`
	CreatedAt        sql.NullTime  `json:"created_at"`
	UpdatedAt        sql.NullTime  `json:"updated_at"`
}

type AssessmentItem struct {
	ID              uuid.UUID      `json:"id"`
	AssessmentID    uuid.UUID      `json:"assessment_id"`
	ItemDescription string         `json:"item_description"`
	Quantity        sql.NullString `json:"quantity"`
	UnitAmount      string         `json:"unit_amount"`
	TotalAmount     string         `json:"total_amount"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type County struct {
	ID              int32          `json:"id"`
	Name            string         `json:"name"`
	Code            string         `json:"code"`
	TreasuryAccount sql.NullString `json:"treasury_account"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type Revenue struct {
	ID              uuid.UUID      `json:"id"`
	TaxpayerID      uuid.UUID      `json:"taxpayer_id"`
	CountyID        int32          `json:"county_id"`
	Amount          string         `json:"amount"`
	RevenueType     string         `json:"revenue_type"`
	TransactionDate time.Time      `json:"transaction_date"`
	Description     sql.NullString `json:"description"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type Taxpayer struct {
	ID           uuid.UUID      `json:"id"`
	CountyID     int32          `json:"county_id"`
	TaxpayerType string         `json:"taxpayer_type"`
	NationalID   string         `json:"national_id"`
	Email        string         `json:"email"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	BusinessName sql.NullString `json:"business_name"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	CountyID     sql.NullInt32  `json:"county_id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	Role         string         `json:"role"`
	EmployeeID   sql.NullString `json:"employee_id"`
	Department   sql.NullString `json:"department"`
	IsActive     sql.NullBool   `json:"is_active"`
	LastLogin    sql.NullTime   `json:"last_login"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
