// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeletePayment(ctx context.Context, id uuid.UUID) error
	GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error)
	// internal/domains/payments/queries/payments.sql
	InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error)
	ListPaymentsByRevenueID(ctx context.Context, assessmentID uuid.NullUUID) ([]Payment, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
