// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"
)

type Querier interface {
	DeleteCounty(ctx context.Context, id int32) error
	GetCountyByID(ctx context.Context, id int32) (County, error)
	InsertCounty(ctx context.Context, arg InsertCountyParams) error
	ListCounties(ctx context.Context, arg ListCountiesParams) ([]County, error)
	UpdateCounty(ctx context.Context, arg UpdateCountyParams) error
}

var _ Querier = (*Queries)(nil)
