// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteRevenue(ctx context.Context, id uuid.UUID) error
	GetRevenueByID(ctx context.Context, id uuid.UUID) (Revenue, error)
	InsertRevenue(ctx context.Context, arg InsertRevenueParams) error
	ListRevenues(ctx context.Context, arg ListRevenuesParams) ([]Revenue, error)
	UpdateRevenue(ctx context.Context, arg UpdateRevenueParams) error
}

var _ Querier = (*Queries)(nil)
