// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Assessment struct {
	ID               uuid.UUID     `json:"id"`
	CountyID         int32         `json:"county_id"`
	TaxpayerID       uuid.UUID     `json:"taxpayer_id"`
	RevenueID        uuid.NullUUID `json:"revenue_id"`
	AssessmentNumber string        `json:"assessment_number"`
	AssessmentType   string        `json:"assessment_type"`
	FinancialYear    string        `json:"financial_year"`
	BaseAmount       string        `json:"base_amount"`
	CalculatedAmount string        `json:"calculated_amount"`
	TotalAmount      string        `json:"total_amount"`
	Status           string        `json:"status"`
	DueDate          time.Time     `json:"due_date"`
	AssessedBy       uuid.NullUUID `json:"assessed_by"`
	AssessedDate     time.Time     `json:"assessed_date"`
	CreatedAt        sql.NullTime  `json:"created_at"`
	UpdatedAt        sql.NullTime  `json:"updated_at"`
}

type AssessmentItem struct {
	ID              uuid.UUID      `json:"id"`
	AssessmentID    uuid.UUID      `json:"assessment_id"`
	ItemDescription string         `json:"item_description"`
	Quantity        sql.NullString `json:"quantity"`
	UnitAmount      string         `json:"unit_amount"`
	TotalAmount     string         `json:"total_amount"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type County struct {
	ID              int32          `json:"id"`
	Name            string         `json:"name"`
	Code            string         `json:"code"`
	TreasuryAccount sql.NullString `json:"treasury_account"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type Payment struct {
	ID                    uuid.UUID      `json:"id"`
	CountyID              int32          `json:"county_id"`
	TaxpayerID            uuid.UUID      `json:"taxpayer_id"`
	AssessmentID          uuid.NullUUID  `json:"assessment_id"`
	PaymentNumber         string         `json:"payment_number"`
	Amount                string         `json:"amount"`
	PaymentMethod         string         `json:"payment_method"`
	PaymentChannel        sql.NullString `json:"payment_channel"`
	ExternalTransactionID sql.NullString `json:"external_transaction_id"`
	PayerPhoneNumber      sql.NullString `json:"payer_phone_number"`
	PayerName             sql.NullString `json:"payer_name"`
	PaymentDate           sql.NullTime   `json:"payment_date"`
	Status                string         `json:"status"`
	CollectedBy           uuid.NullUUID  `json:"collected_by"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	UpdatedAt             sql.NullTime   `json:"updated_at"`
	MpesaReceiptNumber    sql.NullString `json:"mpesa_receipt_number"`
	BankReference         sql.NullString `json:"bank_reference"`
	ChequeNumber          sql.NullString `json:"cheque_number"`
	FailureReason         sql.NullString `json:"failure_reason"`
	CollectionPoint       sql.NullString `json:"collection_point"`
	GpsCoordinates        interface{}    `json:"gps_coordinates"`
	BlockchainHash        sql.NullString `json:"blockchain_hash"`
	BlockNumber           sql.NullInt64  `json:"block_number"`
	Reconciled            sql.NullBool   `json:"reconciled"`
	ReconciliationDate    sql.NullTime   `json:"reconciliation_date"`
	ReconciledBy          uuid.NullUUID  `json:"reconciled_by"`
}

type PaymentAllocation struct {
	ID              uuid.UUID      `json:"id"`
	PaymentID       uuid.UUID      `json:"payment_id"`
	AssessmentID    uuid.UUID      `json:"assessment_id"`
	AllocatedAmount string         `json:"allocated_amount"`
	AllocationType  sql.NullString `json:"allocation_type"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type Receipt struct {
	ID                 uuid.UUID      `json:"id"`
	PaymentID          uuid.UUID      `json:"payment_id"`
	ReceiptNumber      string         `json:"receipt_number"`
	ReceiptType        sql.NullString `json:"receipt_type"`
	PdfFilePath        sql.NullString `json:"pdf_file_path"`
	PdfFileSize        sql.NullInt32  `json:"pdf_file_size"`
	PdfGenerated       sql.NullBool   `json:"pdf_generated"`
	SmsSent            sql.NullBool   `json:"sms_sent"`
	SmsSentAt          sql.NullTime   `json:"sms_sent_at"`
	EmailSent          sql.NullBool   `json:"email_sent"`
	EmailSentAt        sql.NullTime   `json:"email_sent_at"`
	BlockchainHash     string         `json:"blockchain_hash"`
	BlockNumber        sql.NullInt64  `json:"block_number"`
	BlockchainVerified sql.NullBool   `json:"blockchain_verified"`
	QrCodeData         sql.NullString `json:"qr_code_data"`
	CreatedAt          sql.NullTime   `json:"created_at"`
}

type Revenue struct {
	ID              uuid.UUID      `json:"id"`
	TaxpayerID      uuid.UUID      `json:"taxpayer_id"`
	CountyID        int32          `json:"county_id"`
	Amount          string         `json:"amount"`
	RevenueType     string         `json:"revenue_type"`
	TransactionDate time.Time      `json:"transaction_date"`
	Description     sql.NullString `json:"description"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type Taxpayer struct {
	ID           uuid.UUID      `json:"id"`
	CountyID     int32          `json:"county_id"`
	TaxpayerType string         `json:"taxpayer_type"`
	NationalID   string         `json:"national_id"`
	Email        string         `json:"email"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	BusinessName sql.NullString `json:"business_name"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	CountyID     sql.NullInt32  `json:"county_id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	Role         string         `json:"role"`
	EmployeeID   sql.NullString `json:"employee_id"`
	Department   sql.NullString `json:"department"`
	IsActive     sql.NullBool   `json:"is_active"`
	LastLogin    sql.NullTime   `json:"last_login"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
