// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"

	"github.com/google/uuid"
)

type County struct {
	ID              int32          `json:"id"`
	Name            string         `json:"name"`
	Code            string         `json:"code"`
	TreasuryAccount sql.NullString `json:"treasury_account"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	CountyID     sql.NullInt32  `json:"county_id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	Role         string         `json:"role"`
	EmployeeID   sql.NullString `json:"employee_id"`
	Department   sql.NullString `json:"department"`
	IsActive     sql.NullBool   `json:"is_active"`
	LastLogin    sql.NullTime   `json:"last_login"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
